### ISSUE TITLE
Can this example run on RASPI4?

### ISSUE THREAD

**Issue by dirkliebich** [google-coral/project-bodypix#10]
I always run into **segementation** errors. Wonder if this a performance issue with CORAL USB on RASPI

**Comment by Namburger** [comment]
@Moehrenbaum yes it should be able to, however, we recently had some API changes that broke this repo. We're working on getting this fixed, please expects a few weeks!

**Comment by dirkliebich** [comment]
Is there any update regarding the proposed fixes to run on raspi 4? Thx

**Comment by manoj7410** [comment]
@Moehrenbaum Is this issue still reproducible ?

**Comment by metasteve** [comment]
wondering if this now works on raspberry pi ?

**Comment by codyrushing** [comment]
@Moehrenbaum @metasteve I've been successfully running this project on a Raspberry Pi 4 with a USB accelerator.  Here are a couple of changes that I had to make in order to make it work on the Pi:

https://github.com/codyrushing/project-bodypix/#raspberry-pi-notes

Note that the framerates/accuracy on the Pi will be much lower than the examples in the README of this project, even with a USB accelerator.  I was getting ~7 FPS on the default model with 640x480 resolution.  Not terrible, but not good enough for my project.
