### ISSUE TITLE
Usage of your BodyPix models on RPi without TPU accelerator

### ISSUE THREAD

**Issue by mcwoojcik** [google-coral/project-bodypix#4]
Hello, is it possible to use your BodyPix models which are optimized for TPU only on RPi (without accelerator)? I obtained during AllocateTensors(): 
_ERROR: Encountered unresolved custom op: edgetpu-custom-op.
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare._
So I suppose that I can't. 

In other way - is it possible to find just .tflite or .pb version of BodyPix model? 

Thank you in advance

**Comment by Namburger** [comment]
@mcwoojcik Currently the [BasicEngine](https://github.com/google-coral/project-bodypix/blob/master/pose_engine.py#L24) will requires that the model is [edgetpu compiled](https://github.com/google-coral/edgetpu/blob/master/src/cpp/basic/basic_engine_native.cc#L87), so even with the tflite models, you'd need to re-implement pose_engine to use the tflite API instead of the edgetpu api.

**Comment by de-code** [comment]
Hi @Namburger I created [tf-bodypix](https://github.com/de-code/python-tf-bodypix) (based on other great work). It doesn't have the pose detection yet. I am wondering whether you think it would be feasible to have one core project being able to support regular TensorFlow, TensorFLow Lite as well as well as the EdgeTPU? Or do you think that would be fundamentally difficult?
(It just seems there is some duplication in re-implementing the pose detection for example)

**Comment by Naveen-Dodda** [comment]
@de-code, technically it is feasible to have everything related to bodypix at one place. But as of now we don't have any plans or goals aligned to do this. I would take this feedback to the team. 

As your questions has been answered I am closing this for now.
