### ISSUE TITLE
Image import example

### ISSUE THREAD

**Issue by blackus3r** [google-coral/project-bodypix#7]
Is there any example available which accepts the path to an image and then outputs the number of persons on the given picture?

**Comment by Namburger** [comment]
Do you mean just counting the numbers of people in an image? Because in that case it's probably much easier to starts with the [object detection demo](https://github.com/google-coral/tflite/tree/master/python/examples/detection) and increment the count each time [obj.id](https://github.com/google-coral/tflite/blob/master/python/examples/detection/detect_image.py#L117) == 0 (where [0 mapped to person](https://github.com/google-coral/edgetpu/blob/master/test_data/coco_labels.txt#L1)).

**Comment by blackus3r** [comment]
Yes, simple counting random people on pictures. 
I've downloaded the model MobileNet SSD v2 (COCO) from https://coral.ai/models/ but this model does not work very well with our pictures. 
We wrote a test script in nodejs with tensorflowJS and this worked excellent but the performance wasn't good with our hardware. So we decided to test the coral dev board with the models from this repository.

**Comment by Namburger** [comment]
@blackus3r I see, mobilenet architect isn't great with small objects, it's possible that the human are too small?
We have an example where we worked this out by splitting the image to smaller tiles and do inference on individual tiles before putting everything back together. I'm not sure when it will be released though :/

**Comment by Namburger** [comment]
Here we go: https://github.com/google-coral/pycoral/blob/master/examples/small_object_detection.py

@blackus3r but back to your og question, you can also just count `len(poses)` from the outputs of [DetectPoseInImage](https://github.com/google-coral/project-bodypix/blob/master/pose_engine.py#L198)

**Comment by Naveen-Dodda** [comment]
@blackus3r I hope you are able to run inference on input image to count people. I am closing this for now as you have all the info you need.
